### ISSUE TITLE
[How to?] Joint analysis of multiple datasets

### ISSUE THREAD

**Issue by ashipde** [bhklab/MetaGxBreast#5]
Thank you for creating this valuable resource.

I am interested in examining the association of a specific gene with survival. For this, I want to perform a survival analysis of multiple datasets together.

I assume I can combine expression data of the gene from the multiple sets without any need for post-processing like batch-effect adjustment. Please correct me if I am wrong.

How do I go about putting together the gene expression and meta (clinical) data of the multiple datasets? Is there a simple command to do this?

**Comment by ChristopherEeles** [comment]
Hi @ashipde,

For more information on the data in this package, I recommend consulting the [original publication](https://www.nature.com/articles/s41598-019-45165-4).

To ensure comparability between the datasets, they should be loaded using the `rescale` parameter set to TRUE:
```
breastData <- loadBreastDatasets(rescale=TRUE)
```

You can find more information on other parameters to the `loadBreastDatasets` in the help pages. Just load the `MetaGxBreast` package and type `?loadBreastDatasets` into the R console to view them. Alternatively, you can look at the pdf manual on the [MetaGxBreast Bioconductor page](https://bioconductor.org/packages/release/data/experiment/html/MetaGxBreast.html) to view information on all the package functions.

Since the data is stored in `SummarizedExperiment` objects subsetting and combining them should be relatively straightforward, check out the [vignettes on Bioconductor](https://bioconductor.org/packages/release/bioc/html/SummarizedExperiment.html) for more information.

If you want to work with all datasets at once you could also use the `MutliAssayExperiment` object, which provides convenience functions for working with a list of `SummarizedExperiment` objects. See https://bioconductor.org/packages/release/bioc/html/MultiAssayExperiment.html for more information.

Once you have your data combined and ready for survival analysis, you could check out our lab's package for the survival meta-analysis: [survcomp](https://www.bioconductor.org/packages/release/bioc/html/survcomp.html).

Best,
Christopher Eeles
